name: ROCm_installer_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - streamlit
  - psutil
  - pywin32
  - pyyaml
  - rich
  - typer
  - requests
  - pytest
  - black
  - flake8
  - pip:
      - anthropic  # for Claude Code CLI if needed
      - streamlit-option-menu
      - wmi  # for Windows hardware detection